resources:
- resources/namespace.yml
- resources/bootstrap.job.yml
- resources/backend.deployment.yml
- resources/backend.service.yml
- resources/frontend.deployment.yml
- resources/frontend.service.yml

configMapGenerator:
- name: mediawiki-environment
  envs:
  - configs/mediawiki.env

secretGenerator:
- name: mediawiki-secrets
  envs:
  - secrets/mediawiki.properties
