apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: geekshubs-academy-registry
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: k3d
registry: geekshubs-academy-registry
name: k3d-geekshubs-academy-cluster
